/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VoyageSurMesureRouteImport } from './routes/voyage-sur-mesure'
import { Route as DestinationsSlugRouteImport } from './routes/destinations/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyageSurMesureRoute = VoyageSurMesureRouteImport.update({
  id: '/voyage-sur-mesure',
  path: '/voyage-sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRoute
  '/experiences': typeof ExperiencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voyage-sur-mesure': typeof VoyageSurMesureRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRoute
  '/experiences': typeof ExperiencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voyage-sur-mesure': typeof VoyageSurMesureRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/entreprises': typeof EntreprisesRoute
  '/experiences': typeof ExperiencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voyage-sur-mesure': typeof VoyageSurMesureRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/entreprises'
    | '/experiences'
    | '/sitemap.xml'
    | '/voyage-sur-mesure'
    | '/destinations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/entreprises'
    | '/experiences'
    | '/sitemap.xml'
    | '/voyage-sur-mesure'
    | '/destinations/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/entreprises'
    | '/experiences'
    | '/sitemap.xml'
    | '/voyage-sur-mesure'
    | '/destinations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EntreprisesRoute: typeof EntreprisesRoute
  ExperiencesRoute: typeof ExperiencesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VoyageSurMesureRoute: typeof VoyageSurMesureRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyage-sur-mesure': {
      id: '/voyage-sur-mesure'
      path: '/voyage-sur-mesure'
      fullPath: '/voyage-sur-mesure'
      preLoaderRoute: typeof VoyageSurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EntreprisesRoute: EntreprisesRoute,
  ExperiencesRoute: ExperiencesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VoyageSurMesureRoute: VoyageSurMesureRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
